export const FETCH_RECIPE = 'FETCH_RECIPE'
export const FETCH_RECIPE_SUCCESS = 'FETCH_RECIPE_SUCCESS'
export const FETCH_RECIPE_ERROR = 'FETCH_RECIPE_ERROR'

export const FETCH_RECIPE_CREATE = 'FETCH_RECIPE_CREATE'
export const FETCH_RECIPE_CREATE_SUCCESS = 'FETCH_RECIPE_CREATE_SUCCESS'
export const FETCH_RECIPE_CREATE_ERROR = 'FETCH_RECIPE_CREATE_ERROR'

export const FETCH_RECIPE_EDIT = 'FETCH_RECIPE_EDIT'
export const FETCH_RECIPE_EDIT_SUCCESS = 'FETCH_RECIPE_EDIT_SUCCESS'
export const FETCH_RECIPE_EDIT_ERROR = 'FETCH_RECIPE_EDIT_ERROR'

export const FETCH_RECIPE_DELETE = 'FETCH_RECIPE_DELETE'
export const FETCH_RECIPE_DELETE_SUCCESS = 'FETCH_RECIPE_DELETE_SUCCESS'
export const FETCH_RECIPE_DELETE_ERROR = 'FETCH_RECIPE_DELETE_ERROR'

export const TOGGLE_ALERT = 'TOGGLE_ALERT'
export const TOGGLE_LOADER = 'TOGGLE_LOADER'
export const TOGGLE_REDIRECT = 'TOGGLE_REDIRECT'
